#' Import tourist accomodation data from the FSO (dederal office for statistics).
#' @param db_connection
import_fso_tourist_accommodation <- function(
  db_connection, table_name = "ext_fso_tourist_accommodation"
) {
  SOURCE_LINK <- "https://www.pxweb.bfs.admin.ch/sq/57be922e-05fb-4cad-ab19-bd823c54fb1d"  # Generated by visiting https://www.bfs.admin.ch/bfs/en/home/statistics/tourism.assetdetail.14167010.html and clicking "save query" and choosing comma-delimited as output
  tourists <- read.csv(url(SOURCE_LINK), sep = ";", stringsAsFactors = F) 
  tourists[tourists == "..."] <- NA
  tourists <- tourists[, colSums(is.na(tourists)) < nrow(tourists)]  # remove all NA columns (countries with no arrivals in any month) because otherwise pivot_longer errors
  
  tourists_transformed <- tourists %>%
    tidyr::pivot_longer(
      cols = colnames(tourists)[grepl(colnames(tourists), pattern = ".Arrivals")],
      names_to = "country", 
      values_to = "n_arrivals", values_drop_na = T) %>%
    mutate(country = gsub(country, pattern = ".Arrivals", replacement = ""),
           country = gsub(country, pattern = "\\.", replacement = " "),
           date = as.Date(paste(Month, "1", Year), format = "%B %d %Y"),
           country = recode(country, "Irland" = "Ireland"),
           iso_country = countrycode::countrycode(sourcevar = country, 
                                               destination = "iso3c", 
                                               origin = "country.name"),
           iso_country = get_standardized_iso_country(
             iso_country = iso_country,
             db_connection = db_connection)) %>%
    group_by(iso_country, date) %>%
      summarize(n_arrivals = sum(as.numeric(n_arrivals)),
                country = paste0(unique(country), collapse = ", ")) %>%
    mutate(date_type = "MONTH")
  
  key_col = c("iso_country", "date")
  update_cols <- colnames(tourists_transformed)[!(colnames(tourists_transformed) %in% key_col)]
  table_spec <- parse_table_specification(
    table_name = table_name, db_connection = db_connection)
  update_table(table_name = table_name, 
               new_table = tourists_transformed, 
               con = db_connection, 
               append_new_rows = T,
               cols_to_update = update_cols, 
               key_col = key_col, 
               table_spec = table_spec)
}

#' Import tourist accomodation data from the FSO (dederal office for statistics).
#' @param db_connection
import_fso_cross_border_commuters <- function(
  db_connection, table_name = "ext_fso_cross_border_commuters"
) {
  SOURCE_LINK <- "https://www.pxweb.bfs.admin.ch/sq/515c648c-fd39-46a9-a1c1-6584d1b79ee1"  # Generated by visiting https://www.bfs.admin.ch/bfs/de/home/statistiken/arbeit-erwerb/erhebungen/ggs.assetdetail.14776356.html and clicking "save query" and choosing comma-delimited as output
  commuters <- read.csv(url(SOURCE_LINK), sep = ";", check.names = F, 
                        encoding = "latin1", stringsAsFactors = F) 
  commuters[commuters == "..."] <- NA
  colnames(commuters) <- tolower(colnames(commuters))
  
  commuters_transformed <- commuters %>%
    tidyr::pivot_longer(
      cols = colnames(commuters)[grepl(colnames(commuters), pattern = "q")],
      names_to = "quarter", 
      values_to = "n_permits", values_drop_na = T) %>%
    tidyr::separate(col = quarter, into = c("year", "quarter"), sep = "q") %>%
    rename("country" = "wohnsitzstaat") %>%
    mutate(
      month = case_when(quarter == 1 ~ 1, quarter == 2 ~ 4,
                        quarter == 3 ~ 7, quarter == 4 ~ 10),
      date = as.Date(paste(month, "1", year), format = "%m %d %Y"),
      wirtschaftsabteilung = gsub(x = wirtschaftsabteilung, 
                                  pattern = "> ", replacement = ""),
      country = recode(country, "Oesterreich" = "Österreich"),
      iso_country = countrycode::countrycode(sourcevar = country, 
                                          destination = "iso3c", 
                                          origin = "country.name.de"),
      iso_country = get_standardized_iso_country(
        iso_country = iso_country,
        db_connection = db_connection)) %>%
    group_by(iso_country, date, wirtschaftsabteilung) %>%
    summarize(n_permits = sum(as.numeric(n_permits)),
              country = paste0(unique(country), collapse = ", ")) %>%
    mutate(date_type = "QUARTER")
  
  key_col = c("iso_country", "date", "wirtschaftsabteilung")
  update_cols <- colnames(commuters_transformed)[!(colnames(commuters_transformed) %in% key_col)]
  table_spec <- parse_table_specification(table_name = table_name,
                                          db_connection = db_connection)
  update_table(table_name = table_name, 
               new_table = commuters_transformed, 
               con = db_connection, 
               append_new_rows = T,
               cols_to_update = update_cols, 
               key_col = key_col, 
               table_spec = table_spec)
}
