default:
  database:
    local:
      host: localhost
      port: 5432
      username: postgres
      dbname: sars_cov_2
    server:
      host:
      port:
      username:
      dbname:
      password:
