authors:
  eoc: Spina Valeria Romina, Gloria Gaudio, Gladys Martinetti Lucchini
  ethz: Chaoran Chen, Sarah Nadeau, Louis du Plessis, Ivan Topolsky, Kim Philipp Jablonski, Lara Fuhrmann, David Dreifuss, Pelin Burcak Icer, Matteo Carrara, Shuqing Yu, Franziska Singer, Niko Beerenwinkel, Tanja Stadler
  fgcz: Catharine Aquino Fournier, Daniel Ehrsam, Isabel Stürmer, Andreia Cabral de Gouvea, Maria Domenica Moccia, Simon Grüter, Timothy Sykes, Lennart Opitz, Hai Bui, Christian Urban, Griffin White, Laura Neff, Doris Popovic, Andrea Patrignani, Jay Tracy, Ralph Schlapbach
  gfb: Christian Beisel, Tobias Schär, Ina Nissen, Natascha Santacroce, Rebecca Denes, Mirjam Feldkamp, Elodie Burcklen
  imv: Verena Kufner, Maryam Zaheri, Stefan Schmutz, Kevin Steiner, Riccarda Capaul, Guido Bloemberg, Michael Huber, Alexandra Trkola
  teamw: Rebekka Pohl, Monika Bucher, Andreas Lindauer, Andreas Grutsch
  viollier: Andrea Patrizia Salzmann, Henriette Kurth, Christiane Beckmann, Maurice Redondo, Olivier Kobel, Christoph Noppen, Sebastian Kurscheid
involved_labs:
  viollier
  eoc
  imv
  teamw
mandatory_metadata_columns:
  orig_fasta_name
  strain_name
  isolation_date
  location_general
  isolation_source_description
  sequencing_purpose
  library_preparation_kit
  sequencing_platform
  assembly_method
  reporting_lab_name
  reporting_lab_order_id
  collecting_lab_name
  collecting_lab_code
  collecting_lab_order_id
  reporting_authors
  orig_fastq_name_forward
