authors:
  gfb: Christian Beisel, Sarah Nadeau, Chaoran Chen, Louis du Plessis, Ivan Topolsky, Kim Philipp Jablonski, Lara Fuhrmann, David Dreifuss, Pelin Icer, Tobias Schär, Ina Nissen, Natascha Santacroce, Rebecca Denes, Mirjam Feldkamp, Elodie Burcklen, Christiane Beckmann, Matteo Carrara, Shuqing Yu, Franziska Singer, Andrea Patrizia Salzmann, Henriette Kurth, Maurice Redondo, Olivier Kobel, Christoph Noppen, Niko Beerenwinkel, Tanja Stadler
  fgcz_viollier: Chaoran Chen, Sarah Nadeau, Louis du Plessis, Catharine Aquino Fournier, Andrea Patrizia Salzmann, Henriette Kurth, Ivan Topolsky, Kim Philipp Jablonski, Lara Fuhrmann, David Dreifuss, Pelin Icer, Daniel Ehrsam, Isabel Stürmer, Andreia Cabral de Gouvea, Maria Domenica Moccia, Simon Grüter, Timothy Sykes, Lennart Opitz, Hai Bui, Christian Urban, Matteo Carrara, Shuqing Yu, Franziska Singer, Griffin White, Laura Neff, Doris Popovic, Andrea Patrignani, Jay Tracy, Ralph Schlapbach, Christiane Beckmann, Maurice Redondo, Olivier Kobel, Christoph Noppen, Niko Beerenwinkel, Tanja Stadler
  h2030: Chaoran Chen, Sarah Nadeau, Louis du Plessis, Ivan Topolsky, Keith Harshman, Ioannis Xenarios, Cedric Howald, Lorenzo Cerutti, Henri Pegeot, Melyssa Elies, Anthony Blin, Deborah Penet, Jerome Thomas,  Arnaud Hungler, Ilya Kolpakov, Arkadiy Shevrikuko, Katrin Männik, Kim Philipp Jablonski, Lara Fuhrmann, David Dreifuss, Pelin Icer, Christiane Beckmann, Matteo Carrara, Shuqing Yu, Franziska Singer, Andrea Patrizia Salzmann, Henriette Kurth, Maurice Redondo, Olivier Kobel, Christoph Noppen, Niko Beerenwinkel, Tanja Stadler
  viollier: Andrea Patrizia Salzmann, Henriette Kurth, Christiane Beckmann, Ivan Topolsky, Chaoran Chen, Sarah Nadeau, Louis du Plessis, Kim Philipp Jablonski, Lara Fuhrmann, David Dreifuss, Pelin Icer, Matteo Carrara, Shuqing Yu, Franziska Singer, Niko Beerenwinkel, Christoph Noppen, Olivier Kobel, Maurice Redondo, Tanja Stadler
  fgcz_teamw: Ivan Topolsky, Sarah Nadeau, Chaoran Chen, Louis du Plessis, Rebekka Pohl, Monika Bucher, Andreas Lindauer, Catharine Aquino Fournier, Daniel Ehrsam, Isabel Stürmer, Andreia Cabral de Gouvea, Maria Domenica Moccia, Simon Grüter, Timothy Sykes, Lennart Opitz, Hai Bui, Christian Urban, Matteo Carrara, Shuqing Yu, Franziska Singer, Griffin White, Laura Neff, Doris Popovic, Andrea Patrignani, Jay Tracy, Ralph Schlapbach, Ivan Topolsky, Kim Philipp Jablonski, Lara Fuhrmann, David Dreifuss, Pelin Icer, Niko Beerenwinkel, Tanja Stadler
mandatory_metadata_columns:
  orig_fasta_name
  strain_name
  isolation_date
  location_general
  isolation_source_description
  sequencing_purpose
  library_preparation_kit
  sequencing_platform
  assembly_method
  reporting_lab_name
  reporting_lab_order_id
  collecting_lab_name
  collecting_lab_code
  collecting_lab_order_id
  reporting_authors
  orig_fastq_name_forward
raw_data_upload:
  server: euler.ethz.ch
  user: [USER]
  uploads_folder: /cluster/project/panglin/working/uploads
  private_key_euler: "id_ed25519_euler"
  passphrase: TOBEFILLEDIN
  max_conn: 10
  max_samples_per_call: 200
