authors:
  gfb: "Christian Beisel, Sarah Nadeau, Chaoran Chen, Louis du Plessis, Ivan Topolsky, Kim Philipp Jablonski, Lara Fuhrmann, Rebecca Denes, Mirjam Feldkamp, Ina Nissen, Natascha Santacroce, Elodie Burcklen, Christiane Beckmann, Maurice Redondo, Olivier Kobel, Christoph Noppen, Niko Beerenwinkel, Tanja Stadler"
  fgcz: "Chaoran Chen, Sarah Nadeau, Louis du Plessis, Catharine Aquino, Ivan Topolsky, Kim Philipp Jablonski, Lara Fuhrmann, Daniel Ehrsam, Isabel St端rmer, Andreia Cabral de Gouvea, Maria Domenica Moccia, Simon Gr端ter, Timothy Sykes, Lennart Opitz, Griffin White, Laura Neff, Doris Popovic, Andrea Patrignani, Jay Tracy, Ralph Schlapbach, Christiane Beckmann, Maurice Redondo, Olivier Kobel, Christoph Noppen, Niko Beerenwinkel, Tanja Stadler"
  h2030: "Chaoran Chen, Sarah Nadeau, Louis du Plessis, Ivan Topolsky, Emmanouil Dermitzakis, Keith Harshman, Ioannis Xenarios, Henri Pegeot, Lorenzo Cerutti, Deborah Penet, Kim Philipp Jablonski, Lara Fuhrmann, Christiane Beckmann, Maurice Redondo, Olivier Kobel, Christoph Noppen, Niko Beerenwinkel, Tanja Stadler"
  viollier: "Andrea Patrizia Salzmann, Henriette Kurth, Christiane Beckmann, Ivan Topolsky, Chaoran Chen, Sarah Nadeau, Louis du Plessis, Kim Philipp Jablonski, Lara Fuhrmann, Niko Beerenwinkel, Christoph Noppen, Olivier Kobel, Maurice Redondo, Tanja Stadler"
  teamw: "Ivan Topolsky, Sarah Nadeau, Chaoran Chen, Louis du Plessis, Rebekka Pohl, Monika Bucher, Andreas Lindauer, Catharine Aquino, Daniel Ehrsam, Isabel St端rmer, Andreia Cabral de Gouvea, Maria Domenica Moccia, Simon Gr端ter, Timothy Sykes, Lennart Opitz, Griffin White, Laura Neff, Doris Popovic, Andrea Patrignani, Jay Tracy, Ralph Schlapbach, Kim Philipp Jablonski, Lara Fuhrmann, Niko Beerenwinkel, Tanja Stadler"
mandatory_metadata_columns:
  orig_fasta_name
  strain_name
  isolation_date
  location_general
  isolation_source_description
  sequencing_purpose
  library_preparation_kit
  sequencing_platform
  assembly_method
  reporting_lab_name
  reporting_lab_order_id
  collecting_lab_name
  collecting_lab_code
  collecting_lab_order_id
  reporting_authors
  orig_fastq_name_forward
